services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: unless-stopped
    image: postgres:14.1
    expose:
      - '5432'

  redis:
    restart: unless-stopped
    image: redis:6.2
    expose:
      - '6379'

  app:
    environment:
      DJANGO_SECRET_KEY: changeme
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      REDIS_URL: redis://redis
      DJANGO_SETTINGS_MODULE: gestaoestoque.settings
      NPM_WATCH: 'on'
      DJANGO_SETTINGS_DEBUG: 'false'
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/wagtail/:rw
    links:
      - db:db
      - redis:redis
    ports:
      - '8080:8080'
    depends_on:
      - db
      - redis
